name: valgrind

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!.gitignore'
      - '!LICENSE'
      - '!README.md'
      - '!docs/**'
      - '!examples/**'
      - '.github/workflows/tsan.yml'
      - '.github/workflows/valgrind.yml'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: install valgrind
        run: sudo apt-get update && sudo apt-get install valgrind
      - name: build
        run: |
          make BUILD_TYPE=RelWithDebInfo
